# coding: utf-8

"""
    My API

    A description of the API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_checkin_links(self) -> None:
        """Test case for get_checkin_links

        Get check-in links
        """
        pass


if __name__ == '__main__':
    unittest.main()
