# coding: utf-8

"""
    My API

    A description of the API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_checkin_links200_response import GetCheckinLinks200Response

class TestGetCheckinLinks200Response(unittest.TestCase):
    """GetCheckinLinks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCheckinLinks200Response:
        """Test GetCheckinLinks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCheckinLinks200Response`
        """
        model = GetCheckinLinks200Response()
        if include_optional:
            return GetCheckinLinks200Response(
                checkin_link = 'https://example.com/checkin/PNR_VALUE'
            )
        else:
            return GetCheckinLinks200Response(
        )
        """

    def testGetCheckinLinks200Response(self):
        """Test GetCheckinLinks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
